TRANSLATIONS = {
    "ja": {
        "app_title": "鳴潮 音骸スコア計算機",
        "char_setting_title": "キャラクター設定",
        "char_name": "キャラクター名:",
        "char_name_en": "英語名:",
        "char_name_en_placeholder": "英語名を入力 (例: Calcharo)",
        "cost_config": "コスト構成:",
        "echo_5_slot_config": "エコー5枠構成",
        "cost_echo": "コスト{}エコー",
        "effective_substats_weights": "有効サブステータスと重み係数入力欄（5個）",
        "effective_substat_n": "有効サブステータス{}",
        "weight": "重み:",
        "save": "保存",
        "close": "閉じる",
        "error": "エラー",
        "enter_char_name": "キャラクター名を入力してください",
        "enter_char_name_en": "英語名を入力してください",
        "base_stat_offsets": "基礎ステータス・武器補正 (Base/Weapon Offsets)",
        "scaling_stat_label": "参照ステータス:",
        "base_stat_label": "基礎値 (本体+武器):",
        "ideal_stat_label": "理想値 (目標ステ):",
        "crit_offset": "クリ補正:",
        "crit_offset_tooltip": "武器や基礎ステータスによるクリティカル率の合計値を入力。CV計算の目標達成度判定に使用します。",
        "echo_main_stat_unselected": "エコー{}メインステータス未選択",
        "save_complete": "保存完了",
        "save_msg": "{}の設定を保存しました",
        "basic_settings": "基本設定",
        "character": "キャラ:",
        "input_mode": "入力:",
        "manual": "手動",
        "ocr": "OCR",
        "auto_main": "メイン自動",
        "auto_calculate": "自動計算",
        "calc_mode": "計算:",
        "methods_label": "評価方式:",
        "batch": "一括",
        "single_only": "選択のみ",
        "calculate": "計算",
        "set_equipped": "現在装備に設定",
        "vs_equipped": "装備との差分",
        "export_txt": "TXT出力",
        "clear_all": "全クリア",
        "clear_tab": "タブクリア",
        "char_setting": "キャラ設定",
        "help": "ヘルプ",
        "ocr_image": "OCR画像",
        "load_image": "画像読込",
        "paste_clipboard": "クリップボードから貼付 (Ctrl+V)",
        "perform_crop": "切り取り実行",
        "crop_mode": "切り取りモード:",
        "drag": "ドラッグ",
        "percent": "％指定",
        "left_percent": "左%:",
        "top_percent": "上%:",
        "width_percent": "幅%:",
        "height_percent": "高%:",
        "no_image": "No Image",
        "calc_result": "計算結果",
        "log": "ログ",
        "calculator": "計算",
        "settings": "設定",
        "general_settings": "一般設定",
        "calculation_settings": "計算・評価設定",
        "ocr_settings": "OCR・クロップ設定",
        "actions": "アクション",
        "main_stat": "メイン",
        "substats": "サブステータス",
        "ratio": "倍率: {}",
        "tab_clear_success": "タブ '{}' をクリアしました",
        "export_success": "エクスポート成功",
        "export_msg": "結果をTXTファイルにエクスポートしました。",
        "ocr_library_missing": "OCRモードには以下のライブラリが必要です:\n{}\n\n手動モードに戻します。",
        "ocr_auto_fill_fail_no_tab": "OCR自動入力失敗: タブが選択されていません",
        "ocr_auto_fill_fail_tab_not_found": "OCR自動入力失敗: タブ'{}'が見つかりません",
        "ocr_auto_fill_success": "OCR自動入力: サブ{} → {} {}{}",
        "clipboard_no_image": "クリップボードに画像がありません",
        "clipboard_error": "クリップボード読み込みエラー: {}",
        "image_not_loaded": "画像が読み込まれていません",
        "file_not_found": "ファイルが見つかりません:\n{}",
        "image_select_cancelled": "画像選択をキャンセルしました",
        "select_image_file": "画像ファイルを選択 (最大5枚)",
        "image_files": "画像ファイル (最大5枚)",
        "batch_processing_limit_reached": "一括取り込みは最大5枚までです。先頭の5枚のみ処理します。",
        "all_files": "すべてのファイル",
        "pillow_required": "OCRモードを利用するにはPillowが必要です。",
        "crop_cancel": "クロップキャンセル",
        "image_loaded": "画像を読み込みました: {}",
        "ocr_success": "OCR成功 (文字数: {})",
        "ocr_no_text": "OCR結果: テキスト未検出",
        "ocr_tesseract_not_found": "Tesseract実行ファイルが見つかりません (設定: {})",
        "ocr_lang_data_error": "OCR言語データ(jpn)が見つかりません。\nTesseractの日本語辞書(jpn.traineddata)をインストールしてください。\n詳細: {}",
        "ocr_process_error": "OCR処理でエラーが発生しました:\n{}",
        "data_save_success": "データを保存しました",
        "data_load_success": "データ読込完了（必要な項目を反映）",
        "data_load_error": "読込失敗: {}",
        "waiting_for_character": "キャラクターを選択してください。選択後に計算を実行します。",
        "log_waiting_for_character": "キャラクター未選択のため、計算を待機しています。",
        "settings_loaded": "設定を読み込みました",
        "language": "言語 (Language):",
        "restart_required": "再起動が必要です",
        "restart_msg": "言語設定を変更しました。適用するにはアプリケーションを再起動してください。",
        "language_changed_title": "言語変更",
        "language_changed_message": "言語設定を切り替えました。",
        "score_calc_error": "スコア計算エラー: {}",
        "tab_not_selected": "タブが選択されていません",
        "tab_info_error": "タブ情報取得エラー",
        "main_stat_missing": "{}: メインステータスが未入力です",
        "individual_score_title": "【{}】個別スコア計算 - {}\n",
        "echo_info": "【音骸情報】\n",
        "level": "レベル: {}\n",
        "effective_substat_count": "有効サブステ数: {}/5\n\n",
        "substat_header": "【サブステータス】\n",
        "none": "  （なし）\n",
        "score_by_method": "【評価方式別スコア】\n\n",
        "score_label": "   スコア",
        "rating_label": "   評価",
        "desc_label": "   説明",
        "overall_eval": "【総合評価】\n",
        "estimated_total_stats": "【推定トータルステータス】\n",
        "total_score": "総合スコア",
        "overall_rating": "総合評価",
        "recommendation": "推奨度",
        "batch_score_title": "【{}】音骸セット総合評価\n",
        "calculated_count": "計算済み音骸数: {}/{}\n",
        "avg_scores_title": "【{}個の音骸の平均スコア】",
        "average": "平均",
        "total_sum": "スコア合計",
        "total_average": "総合平均",
        "echo_n_header": "\n【音骸 {}】{}\n",
        "set_total_score": "【セット全体の合計スコア】\n",
        "set_avg_score": "【セット全体の平均スコア】\n",
        "final_evaluation": "【最終評価】\n",
        "achievement_rate_label": "厳選達成率",
        "achievement_rate_desc": "理想のサブステ5種がMaxロールだった場合を100%とした達成度",
        "sss_desc": "SSS級 - 完璧な音骸セット！理論値級の性能です",
        "ss_desc": "SS級 - 非常に優秀なセット。ほぼ完成形です",
        "s_desc": "S級 - 優秀なセット。実戦で十分な性能です",
        "a_desc": "A級 - 良好なセット。使用に問題ありません",
        "b_desc": "B級 - 及第点。改善の余地があります",
        "c_desc": "C級 - 要改善。厳選を継続することをお勧めします",
        "normalized_score_desc": "各サブステを最大値で正規化し重み付け",
        "ratio_score_desc": "サブステ比率とダメージ上昇を考慮",
        "roll_quality_desc": "各サブステの引き強度を個別評価",
        "effective_stat_desc": "有効なサブステ数にボーナス付与",
        "normalized_score_label": "正規化スコア方式 (GameWith式)",
        "ratio_score_label": "比率重視方式 (Keisan式)",
        "roll_quality_label": "ロール品質方式",
        "effective_stat_label": "有効ステータス数方式",
        "cost_label": "コスト: {}",
        "score_point": "{:.2f}点",
        "score_per_item": "{:.2f}点/個",
        "score_point_count": "{:.2f}点 [{}個]",
        "total_score_label": "総合スコア",
        "total_label": "総合",
        "normalized_label": "正規化",
        "ratio_label": "比率",
        "roll_label": "ロール",
        "effective_label": "有効ステ",
        "effective_count_label": "有効ステータス数",
        "recommend_label": "推奨",
        "warning": "警告",
        "no_data": "計算可能な音骸データがありません",
        "individual_eval_done": "個別詳細評価完了: {} - 総合{:.2f}点",
        "batch_eval_done": "まとめて詳細評価完了: {}個計算",
        "calc_error": "計算エラー:\n{}",
        "batch_calc_error": "まとめて評価エラー: {}",
        "batch_error_msg": "まとめて計算でエラーが発生しました:\n{}",
        "image_load_error": "画像の読み込みに失敗しました:\n{}",
        "image_load_error_log": "画像読み込みエラー: {}",
        "pytesseract_not_installed": "pytesseractがインストールされていないためOCRを実行できません",
        "tesseract_found_path": "TesseractがPATHから発見されました: {}",
        "tesseract_not_found_sys": "Tesseractが見つかりません。パスを設定するか、システムにインストールしてください。",
        "ocr_error_title": "OCRエラー",
        "ocr_lang_data_error_log": "OCR言語データエラー: {}",
        "tesseract_exec_not_found": "Tesseract実行ファイルが見つかりません:\n{}",
        "tesseract_exec_error_log": "Tesseract実行ファイルエラー: {}",
        "ocr_process_error_log": "OCR処理エラー: {}",
        "ocr_behavior": "OCR挙動設定",
        "skip_duplicate_ocr": "重複データを無視（入力スキップ）",
        "tooltip_skip_duplicate_ocr": "有効にすると、現在画面にあるデータと完全に一致するOCR結果を無視します。\n誤って同じ画像を再度OCRしてしまった場合に、手入力による修正などがリセットされるのを防ぎます。\n（履歴の保存設定とは独立して動作します）",
        "crop_title": "画像切り取り",
        "crop_instruction": "マウスドラッグで切り取り範囲を指定してください。",
        "crop_sync_notice": "※ここで保存した位置(L,T)とサイズ(W,H)は、メイン画面のスライダー(％指定)と同期され、自動計算時に使用されます。",
        "echo_build_title": "音骸ビルド",
        "average_score_label": "平均スコア",
        "cost_label_short": "コスト",
        "crop_confirm_apply": "適用確認",
        "crop_apply_percent": "%設定エリアを適用",
        "crop_apply_percent_tooltip": "選択した領域の幅/高さをパーセントとして扱い、元画像に対して割合で切り取ります。例: 50% x 50%",
        "crop_save_as_default": "設定をメイン画面のスライダーと同期して保存",
        "crop_save_as_default_tooltip": "この範囲(L,T,W,H)をメイン画面の％指定スライダーに即座に反映し、次回以降のデフォルト値（自動計算時の範囲）として保存します。",
        "crop_confirm_needed": "適用するにはチェックボックスをオンにしてください",
        "preset_name_placeholder": "名前",
        "preset_placeholder_format": "L,T,W,H (%)",
        "preset_name_required": "プリセット名を入力してください",
        "preset_format": "プリセット形式が正しくありません (例: 50x50)",
        "ok": "決定",
        "cancel": "キャンセル",
        "reset": "リセット",
        "load": "読込",
        "delete": "削除",
        "info": "情報",
        "crop_too_small": "選択範囲が小さすぎます",
        "text_color": "テキスト色:",
        "select_color": "色選択",
        "apply": "適用",
        "background_image": "背景画像:",
        "select_image": "画像を選択",
        "clear_image": "クリア",
        "bg_opacity": "背景不透明度:",
        "text_shadow": "テキストに影をつける",
        "shadow_color": "影の色:",
        "help_customization": "見た目のカスタマイズ ヘルプ",
        "font_settings": "フォント設定",
        "font_family": "フォント:",
        "default_font": "システムデフォルト",
        "weight_template": "重みテンプレート:",
        "custom": "カスタム",
        "title_warning": "警告",
        "warn_legacy_bg_not_found": "以前設定された背景画像が次の場所に見つかりませんでした:\n\n{0}\n\n設定はクリアされました。",
        # Stats
        "HP": "HP",
        "HP%": "HP%",
        "攻撃力": "攻撃力",
        "攻撃力%": "攻撃力%",
        "防御力": "防御力",
        "防御力%": "防御力%",
        "クリティカル率": "クリティカル率",
        "クリティカルダメージ": "クリティカルダメージ",
        "共鳴効率": "共鳴効率",
        "通常攻撃ダメージアップ": "通常攻撃ダメージアップ",
        "重撃ダメージアップ": "重撃ダメージアップ",
        "共鳴スキルダメージアップ": "共鳴スキルダメージアップ",
        "共鳴解放ダメージアップ": "共鳴解放ダメージアップ",
        "焦熱ダメージアップ": "焦熱ダメージアップ",
        "凝縮ダメージアップ": "凝縮ダメージアップ",
        "電導ダメージアップ": "電導ダメージアップ",
        "気動ダメージアップ": "気動ダメージアップ",
        "回折ダメージアップ": "回折ダメージアップ",
        "消滅ダメージアップ": "消滅ダメージアップ",
        "HP回復効果アップ": "HP回復効果アップ",
        # Ratings
        "rating_sss_norm": "SS級 - 最高品質",
        "rating_ss_norm": "S級 - 優秀",
        "rating_s_norm": "A級 - 実用的",
        "rating_b_norm": "B級 - 要改善",
        "rating_perf_ratio": "完璧 - 理論値に近い",
        "rating_exc_ratio": "優秀 - 十分強い",
        "rating_good_ratio": "良好 - 使用可能",
        "rating_avg_ratio": "普通 - 改善推奨",
        "rating_weak_ratio": "弱い - 厳選必要",
        "rating_god_roll": "神引き - 最高ロール連続",
        "rating_win_roll": "当たり - 高品質ロール多数",
        "rating_avg_roll": "平均的 - 標準的ロール",
        "rating_bad_roll": "ハズレ - 低品質ロール",
        "rating_perf_eff": "完璧 - 5有効ステ ({:.1f}点)",
        "rating_exc_eff": "優秀 - 4有効ステ ({:.1f}点)",
        "rating_good_eff": "良好 - 3有効ステ ({:.1f}点)",
        "rating_bad_eff": "要改善 - {}有効ステ ({:.1f}点)",
        "rating_sss_global": "SSS - 完璧な音骸セット!",
        "rating_ss_global": "SS - 非常に優秀",
        "rating_s_global": "S - 優秀",
        "rating_a_global": "A - 良好",
        "rating_b_global": "B - 合格",
        "rating_c_global": "C - 要改善",
        "rec_continue": "厳選継続",
        "rec_use": "使用推奨",
        "theme": "ライト/ダーク",
        "dark_theme": "ダーク",
        "light_theme": "ライト",
        "clear_theme": "クリア",
        "custom_theme": "カスタム",
        "display_settings": "表示設定",
        # Character Names
        "CarlottaNew": "カルロッタNew",
        "Cantarella": "カンタレラ",
        "Tsubaki": "ツバキ",
        "Changli": "長離",
        "General": "汎用",
        "rating_sss_single": "SSS - 完璧な音骸! 理想的な性能です",
        "rating_ss_single": "SS - 非常に優秀な音骸",
        "rating_s_single": "S - 優秀な音骸",
        "rating_a_single": "A - 良好な音骸",
        "rating_b_single": "B - 使用可能",
        "rating_c_single": "C - 厳選推奨",
        # CV Method Ratings
        "rating_outstanding_cv": "最高級 - 45点以上 (SSS級)",
        "rating_excellent_cv": "非常に優秀 - 38~45点 (S級)",
        "rating_good_cv": "優秀 - 30~38点 (目標達成)",
        "rating_acceptable_cv": "合格 - 25~30点 (最低ライン)",
        "rating_weak_cv": "要厳選 - 25点未満",
        # Method Labels
        "cv_score_label": "CV換算方式 (コミュニティ標準)",
        "cv_score_desc": "会心値を基準とした評価（30点合格/38点目標）",
        # Method Selection
        "calc_methods": "計算方式:",
        "method_normalized": "正規化",
        "method_ratio": "比率重視",
        "method_roll": "ロール品質",
        "method_effective": "有効ステ数",
        "method_cv": "CV換算",
        "no_methods_selected": "少なくとも1つの計算方式を選択してください",
        "cleanup_title": "背景画像のクリーンアップ",
        "cleanup_button": "クリーンアップ",
        "cleanup_no_folder": "imagesフォルダが見つかりません。",
        "cleanup_no_unused": "未使用の背景画像はありません。",
        "cleanup_confirm": "{}個の未使用画像を削除しますか？\n\n{}",
        "cleanup_error": "{}個の画像を削除しましたが、以下のファイルの削除中にエラーが発生しました:\n\n{}",
        "cleanup_success": "{}個の未使用画像を削除しました。",
        "cleanup_unexpected_error": "クリーンアップ中に予期せぬエラーが発生しました:\n{}",
        "new": "新規作成",
        "edit": "編集",
        "char_setting_new": "キャラクター設定(新規)",
        "char_setting_edit": "キャラクター設定(編集)",
        "history_title": "計算履歴",
        "history": "履歴",
        "preprocess_settings": "前処理設定",
        "history_search": "検索:",
        "history_char": "キャラ:",
        "history_cost": "コスト:",
        "history_rating": "評価:",
        "history_from": "開始日:",
        "history_to": "終了日:",
        "history_filter_date": "日付で絞り込む",
        "history_reset": "リセット",
        "history_clear": "履歴を全削除",
        "history_stats": "件数: {} | 平均スコア: {:.2f} | 最高スコア: {:.2f}",
        "history_no_data": "現在の条件に一致するスコアデータはありません。",
        "history_col_time": "日時",
        "history_col_char": "キャラクター",
        "history_col_cost": "コスト",
        "history_col_action": "アクション",
        "history_col_result": "結果",
        "history_duplicate_mode": "重複履歴の挙動:",
        "history_dup_all": "すべて保存 (重複を許可)",
        "history_dup_latest": "最新を保持 (古い履歴を削除)",
        "history_dup_oldest": "最古を保持 (新しい履歴を無視)",
        "history_duplicate_tooltip": "同じステータスの音骸を計算した際の挙動を設定します。\n・すべて保存: 重複を気にせず追加します。\n・最新を保持: 古い履歴を消して、今回計算した時刻で上書きします。\n・最古を保持: 既に履歴にある場合は追加せず、最初に手に入れた（計算した）時刻を維持します。",
        "select_character": "キャラクター選択",
        "select_character_to_edit": "編集するキャラクターを選択してください:",
        "no_characters_found": "キャラクターが見つかりません。",
        "tooltip_char_setting": "キャラクターの追加・編集を行います。",
        "tooltip_display_settings": "背景画像やテーマ、文字色などの見た目をカスタマイズします。",
        "tooltip_history": "過去の計算結果履歴を表示・検索します。",
        "tooltip_preprocess": "OCR精度向上のための画像前処理設定を行います。",
        "tooltip_help": "使い方のヘルプファイルを開きます。",
        "tooltip_load_image": "画像ファイルを読み込んで表示します。",
        "tooltip_paste": "クリップボードの画像を読み込みます (Ctrl+V)。",
        "tooltip_crop": "範囲指定した部分を切り取ってOCRに使用します。",
        "tooltip_auto_calculate": "画像読み込みやOCR完了時に自動で計算を実行します。",
        "tooltip_calculate": "現在の入力値でスコア計算を実行します (F5)。",
        "tooltip_set_equipped": "現在の入力内容をこのキャラの装備済み音骸として保存します。",
        "tooltip_export_txt": "計算結果をテキストファイルに出力します (Ctrl+S)。",
        "scoreboard": "スコアボード",
        "tooltip_scoreboard": "スコアボード画像を生成します。",
        "save_scoreboard": "スコアボードを保存",
        "tooltip_clear_all": "すべての入力内容と画像をクリアします (Ctrl+R)。",
        "tooltip_clear_tab": "現在表示しているタブの内容のみをクリアします。",
        "tooltip_manual_mode": "数値を手入力して計算するモードです。",
        "tooltip_ocr_mode": "画像から数値を自動認識して計算するモードです。",
        "tooltip_batch_mode": "5つの音骸をセットとして総合評価します。",
        "tooltip_single_mode": "選択中の音骸単体の性能を詳細評価します。",
        "apply_selection": "選択範囲を適用",
        "tooltip_apply_selection": "現在ドラッグして選択している範囲をメイン画面の％指定スライダーに同期・保存します。",
    },
    "en": {
        "app_title": "Wuthering Waves Echo Score Calculator",
        "char_setting_title": "Character Settings",
        "char_name": "Character Name:",
        "char_name_en": "English Name:",
        "char_name_en_placeholder": "Enter English name (e.g., Calcharo)",
        "cost_config": "Cost Config:",
        "echo_5_slot_config": "Echo 5-Slot Configuration",
        "cost_echo": "Cost {} Echo",
        "effective_substats_weights": "Effective Substats & Weights (5 slots)",
        "effective_substat_n": "Effective Substat {}",
        "weight": "Weight:",
        "save": "Save",
        "close": "Close",
        "error": "Error",
        "enter_char_name": "Please enter a character name",
        "enter_char_name_en": "Please enter an English name",
        "base_stat_offsets": "Character/Weapon Stat Offsets",
        "scaling_stat_label": "Scaling Stat:",
        "base_stat_label": "Base (Char+Weapon):",
        "ideal_stat_label": "Ideal (Target Stat):",
        "crit_offset": "Crit Offset:",
        "crit_offset_tooltip": "Enter total crit rate from weapon and base stats. Used for CV rating calculation.",
        "echo_main_stat_unselected": "Echo {} Main Stat not selected",
        "save_complete": "Save Complete",
        "save_msg": "Settings for {} saved",
        "basic_settings": "Basic Settings",
        "character": "Char:",
        "input_mode": "Input:",
        "manual": "Manual",
        "ocr": "OCR",
        "auto_main": "Auto Main",
        "auto_calculate": "Auto Calc",
        "calc_mode": "Calc:",
        "methods_label": "Methods:",
        "batch": "Batch",
        "single_only": "Single",
        "calculate": "Calculate",
        "set_equipped": "Set as Equipped",
        "vs_equipped": "vs Equipped",
        "export_txt": "Export TXT",
        "clear_all": "Clear All",
        "clear_tab": "Clear Tab",
        "char_setting": "Char Set",
        "help": "Help",
        "ocr_image": "OCR Image",
        "load_image": "Load Image",
        "paste_clipboard": "Paste Clipboard (Ctrl+V)",
        "perform_crop": "Crop",
        "crop_mode": "Crop Mode:",
        "drag": "Drag",
        "percent": "Percent",
        "left_percent": "L%:",
        "top_percent": "T%:",
        "width_percent": "W%:",
        "height_percent": "H%:",
        "no_image": "No Image",
        "calc_result": "Results",
        "log": "Log",
        "calculator": "Calculator",
        "settings": "Settings",
        "general_settings": "General Settings",
        "calculation_settings": "Calc Settings",
        "ocr_settings": "OCR & Crop",
        "actions": "Actions",
        "main_stat": "Main",
        "substats": "Substats",
        "ratio": "Ratio: {}",
        "tab_clear_success": "Cleared tab '{}'",
        "export_success": "Export Success",
        "export_msg": "Result exported to TXT file.",
        "ocr_library_missing": "OCR mode requires the following libraries:\n{}\n\nReverting to Manual mode.",
        "ocr_auto_fill_fail_no_tab": "OCR Auto-fill Failed: No tab selected",
        "ocr_auto_fill_fail_tab_not_found": "OCR Auto-fill Failed: Tab '{}' not found",
        "ocr_auto_fill_success": "OCR Auto-fill: Sub{} -> {} {}{}",
        "clipboard_no_image": "No image in clipboard",
        "clipboard_error": "Clipboard load error: {}",
        "image_not_loaded": "Image not loaded",
        "file_not_found": "File not found:\n{}",
        "image_select_cancelled": "Image selection cancelled",
        "select_image_file": "Select Image Files (Max 5)",
        "image_files": "Image Files (Max 5)",
        "batch_processing_limit_reached": "Batch processing is limited to 5 images. Only the first 5 will be processed.",
        "all_files": "All Files",
        "pillow_required": "Pillow is required for OCR mode.",
        "crop_cancel": "Crop cancelled",
        "image_loaded": "Image loaded: {}",
        "ocr_success": "OCR Success (Chars: {})",
        "ocr_no_text": "OCR Result: No text detected",
        "ocr_tesseract_not_found": "Tesseract executable not found (Config: {})",
        "ocr_lang_data_error": "OCR language data (jpn) not found.\nPlease install Tesseract Japanese data (jpn.traineddata).\nDetail: {}",
        "ocr_process_error": "OCR Process Error:\n{}",
        "data_save_success": "Data saved",
        "data_load_success": "Data loaded (Applied necessary items)",
        "data_load_error": "Load Failed: {}",
        "waiting_for_character": "Please select a character. Calculation will run after selection.",
        "log_waiting_for_character": "Calculation is waiting for character selection.",
        "settings_loaded": "Settings loaded",
        "language": "Language:",
        "restart_required": "Restart Required",
        "restart_msg": "Language setting changed. Please restart the application to apply.",
        "language_changed_title": "Language Changed",
        "language_changed_message": "Language setting has been switched.",
        "score_calc_error": "Score Calc Error: {}",
        "tab_not_selected": "Tab not selected",
        "tab_info_error": "Tab info error",
        "main_stat_missing": "{}: Main stat missing",
        "individual_score_title": "[{}] Individual Score - {}\n",
        "echo_info": "[Echo Info]\n",
        "level": "Level: {}\n",
        "effective_substat_count": "Effective Substats: {}/5\n\n",
        "substat_header": "[Substats]\n",
        "none": "  (None)\n",
        "score_by_method": "[Score by Method]\n\n",
        "score_label": "   Score",
        "rating_label": "   Rating",
        "desc_label": "   Desc",
        "overall_eval": "[Overall Evaluation]\n",
        "estimated_total_stats": "[Estimated Total Stats]\n",
        "total_score": "Total Score",
        "overall_rating": "Overall Rating",
        "recommendation": "Recommendation",
        "batch_score_title": "[{}] Echo Set Total Evaluation\n",
        "calculated_count": "Calculated Echoes: {}/{}\n",
        "avg_scores_title": "[Average Scores for {} Echoes]",
        "average": "Average",
        "total_sum": "Total Score Sum",
        "total_average": "Overall Average",
        "echo_n_header": "\n[Echo {}] {}\n",
        "set_total_score": "[Set Total Score]\n",
        "set_avg_score": "[Set Average Score]\n",
        "final_evaluation": "[Final Evaluation]\n",
        "achievement_rate_label": "Substat Achievement",
        "achievement_rate_desc": "Percentage relative to theoretical max of top 5 weighted substats",
        "sss_desc": "SSS - Perfect set! Theoretical maximum performance.",
        "ss_desc": "SS - Excellent set. Almost complete.",
        "s_desc": "S - Great set. Sufficient for combat.",
        "a_desc": "A - Good set. No issues using it.",
        "b_desc": "B - Acceptable. Room for improvement.",
        "c_desc": "C - Needs improvement. Keep farming.",
        "normalized_score_desc": "Normalized by max value and weighted",
        "ratio_score_desc": "Considers substat ratio and damage increase",
        "roll_quality_desc": "Evaluates roll quality of each substat",
        "effective_stat_desc": "Bonus for number of effective substats",
        "normalized_score_label": "Normalized Score",
        "ratio_score_label": "Ratio Score",
        "roll_quality_label": "Roll Quality",
        "effective_stat_label": "Effective Stat Count",
        "cost_label": "Cost: {}",
        "score_point": "{:.2f} pts",
        "score_per_item": "{:.2f} pts/item",
        "score_point_count": "{:.2f} pts [{} items]",
        "total_score_label": "Total Score",
        "total_label": "Total",
        "normalized_label": "Norm",
        "ratio_label": "Ratio",
        "roll_label": "Roll",
        "effective_label": "Eff",
        "effective_count_label": "Eff#",
        "recommend_label": "Rec",
        "warning": "Warning",
        "no_data": "No calculable echo data",
        "individual_eval_done": "Individual eval done: {} - Total {:.2f} pts",
        "batch_eval_done": "Batch eval done: {} items calculated",
        "calc_error": "Calc Error:\n{}",
        "batch_calc_error": "Batch calc error: {}",
        "batch_error_msg": "Error in batch calculation:\n{}",
        "image_load_error": "Failed to load image:\n{}",
        "image_load_error_log": "Image load error: {}",
        "pytesseract_not_installed": "pytesseract not installed, cannot perform OCR",
        "tesseract_found_path": "Tesseract found in PATH: {}",
        "tesseract_not_found_sys": "Tesseract not found. Please configure path or install on system.",
        "ocr_error_title": "OCR Error",
        "ocr_lang_data_error_log": "OCR lang data error: {}",
        "tesseract_exec_not_found": "Tesseract executable not found:\n{}",
        "tesseract_exec_error_log": "Tesseract exec error: {}",
        "ocr_process_error_log": "OCR process error: {}",
        "ocr_behavior": "OCR Behavior",
        "skip_duplicate_ocr": "Ignore duplicate data (Skip input)",
        "tooltip_skip_duplicate_ocr": "If enabled, ignores OCR results that are identical to the current screen data.\nPrevents manual edits from being reset if you accidentally OCR the same image again.\n(Operates independently of History duplicate settings)",
        "crop_title": "Crop Image",
        "crop_instruction": "Drag mouse to select crop area.",
        "crop_sync_notice": "* The saved position (L,T) and size (W,H) will sync with the main UI sliders and be used for Auto Calculation.",
        "echo_build_title": "Echo Build",
        "average_score_label": "Average Score",
        "cost_label_short": "Cost",
        "crop_confirm_apply": "Confirm Apply",
        "crop_apply_percent": "Apply as Percentage Area",
        "crop_apply_percent_tooltip": "Treat the width/height of the selected area as a percentage and crop relative to the original image. E.g., 50% x 50%",
        "crop_save_as_default": "Save as Default",
        "crop_save_as_default_tooltip": "Save the current selection (or preset value) as the default for future sessions. Persists after app restart.",
        "crop_confirm_needed": "Please check the box to confirm apply",
        "preset_name_placeholder": "Name",
        "preset_placeholder_format": "L,T,W,H (%)",
        "preset_name_required": "Please enter a preset name",
        "preset_format": "Invalid preset format (e.g., 50x50)",
        "ok": "OK",
        "cancel": "Cancel",
        "reset": "Reset",
        "load": "Load",
        "delete": "Delete",
        "info": "Info",
        "crop_too_small": "Selection area is too small",
        "text_color": "Text Color:",
        "select_color": "Select Color",
        "apply": "Apply",
        "background_image": "Background Image:",
        "select_image": "Select Image",
        "clear_image": "Clear",
        "bg_opacity": "Background Opacity:",
        "text_shadow": "Enable Text Shadow",
        "shadow_color": "Shadow Color:",
        "HP": "HP",
        "HP%": "HP%",
        "攻撃力": "ATK",
        "攻撃力%": "ATK%",
        "防御力": "DEF",
        "防御力%": "DEF%",
        "クリティカル率": "Crit Rate",
        "クリティカルダメージ": "Crit DMG",
        "共鳴効率": "Energy Regen",
        "通常攻撃ダメージアップ": "Basic ATK DMG Bonus",
        "重撃ダメージアップ": "Heavy ATK DMG Bonus",
        "共鳴スキルダメージアップ": "Skill DMG Bonus",
        "共鳴解放ダメージアップ": "Liberation DMG Bonus",
        "焦熱ダメージアップ": "Fusion DMG Bonus",
        "凝縮ダメージアップ": "Glacio DMG Bonus",
        "電導ダメージアップ": "Electro DMG Bonus",
        "気動ダメージアップ": "Aero DMG Bonus",
        "回折ダメージアップ": "Spectro DMG Bonus",
        "消滅ダメージアップ": "Havoc DMG Bonus",
        "HP回復効果アップ": "Healing Bonus",
        # Ratings
        "rating_sss_norm": "SS - Top Quality",
        "rating_ss_norm": "S - Excellent",
        "rating_s_norm": "A - Practical",
        "rating_b_norm": "B - Needs Improvement",
        "rating_perf_ratio": "Perfect - Near Theoretical Max",
        "rating_exc_ratio": "Excellent - Very Strong",
        "rating_good_ratio": "Good - Usable",
        "rating_avg_ratio": "Average - Recommended to Improve",
        "rating_weak_ratio": "Weak - Needs Farming",
        "rating_god_roll": "God Roll - Max Rolls Streak",
        "rating_win_roll": "Win - Many High Rolls",
        "rating_avg_roll": "Average - Standard Rolls",
        "rating_bad_roll": "Loss - Low Quality Rolls",
        "rating_perf_eff": "Perfect - 5 Effective Stats ({:.1f} pts)",
        "rating_exc_eff": "Excellent - 4 Effective Stats ({:.1f} pts)",
        "rating_good_eff": "Good - 3 Effective Stats ({:.1f} pts)",
        "rating_bad_eff": "Improve - {} Effective Stats ({:.1f} pts)",
        "rating_sss_global": "SSS - Perfect Echo Set!",
        "rating_ss_global": "SS - Very Excellent",
        "rating_s_global": "S - Excellent",
        "rating_a_global": "A - Good",
        "rating_b_global": "B - Passing Grade",
        "rating_c_global": "C - Needs Improvement",
        "rec_continue": "Continue Farming",
        "rec_use": "Recommended to Use",
        "theme": "light/dark",
        "dark_theme": "Dark",
        "light_theme": "Light",
        "clear_theme": "Clear",
        "custom_theme": "Custom",
        "display_settings": "Display Settings",
        "rating_sss_single": "SSS - Perfect Echo!",
        "rating_ss_single": "SS - High Quality Echo",
        "rating_s_single": "S - Good Echo",
        "rating_a_single": "A - Decent Echo",
        "rating_b_single": "B - Usable",
        "rating_c_single": "C - Needs Improvement",
        # CV Method Ratings
        "rating_outstanding_cv": "Outstanding - 45+ pts (SSS tier)",
        "rating_excellent_cv": "Excellent - 38~45 pts (S tier)",
        "rating_good_cv": "Good - 30~38 pts (Target Achieved)",
        "rating_acceptable_cv": "Acceptable - 25~30 pts (Passing Grade)",
        "rating_weak_cv": "Weak - Below 25 pts",
        # Method Labels
        "cv_score_label": "CV (Crit Value) Method - Community Standard",
        "cv_score_desc": "Crit-value based evaluation (30pt pass / 38pt target)",
        # Method Selection
        "calc_methods": "Calculation Methods:",
        "method_normalized": "Normalized",
        "method_ratio": "Ratio-Based",
        "method_roll": "Roll Quality",
        "method_effective": "Effective Stats",
        "method_cv": "CV (Crit Value)",
        "no_methods_selected": "Please select at least one calculation method",
        "input_bg_color": "Input Background Color",
        "full_reset": "Reset All Display Settings",
        "confirm_full_reset": "Are you sure you want to reset all display settings?",
        "help_customization": "Customization Guide",
        "font_settings": "Font Settings",
        "font_family": "Font Family:",
        "default_font": "System Default",
        "weight_template": "Weight Template:",
        "custom": "Custom",
        "title_warning": "Warning",
        "warn_legacy_bg_not_found": "The previously set background image could not be found at:\n\n{0}\n\nThe setting has been cleared.",
        "cleanup_title": "Cleanup Background Images",
        "cleanup_button": "Cleanup",
        "cleanup_no_folder": "The 'images' folder was not found.",
        "cleanup_no_unused": "There are no unused background images.",
        "cleanup_confirm": "Are you sure you want to delete {} unused images?\n\n{}",
        "cleanup_error": "Deleted {} images, but an error occurred while deleting the following files:\n\n{}",
        "cleanup_success": "Successfully deleted {} unused images.",
        "cleanup_unexpected_error": "An unexpected error occurred during cleanup:\n{}",
        "new": "New",
        "edit": "Edit",
        "char_setting_new": "Character Settings (New)",
        "char_setting_edit": "Character Settings (Edit)",
        "history_title": "Calculation History",
        "history": "History",
        "preprocess_settings": "Preprocessing",
        "history_search": "Search:",
        "history_char": "Char:",
        "history_cost": "Cost:",
        "history_rating": "Rating:",
        "history_from": "From:",
        "history_to": "To:",
        "history_filter_date": "Filter by Date",
        "history_reset": "Reset",
        "history_clear": "Clear All History",
        "history_stats": "Count: {} | Average: {:.2f} | Max: {:.2f}",
        "history_no_data": "No score data available for current filters.",
        "history_col_time": "Timestamp",
        "history_col_char": "Character",
        "history_col_cost": "Cost",
        "history_col_action": "Action",
        "history_col_result": "Result",
        "history_duplicate_mode": "Duplicate History Behavior:",
        "history_dup_all": "Keep All (Allow Duplicates)",
        "history_dup_latest": "Keep Latest (Remove Old)",
        "history_dup_oldest": "Keep Oldest (Ignore New)",
        "history_duplicate_tooltip": "Sets behavior when an echo with the same stats is calculated.\n- Keep All: Add every time without checking.\n- Keep Latest: Delete old entry and replace with the current result.\n- Keep Oldest: Do nothing if already exists, preserving the original timestamp.",
        "select_character": "Select Character",
        "select_character_to_edit": "Select a character to edit:",
        "no_characters_found": "No characters found.",
        "tooltip_char_setting": "Add or edit character profiles.",
        "tooltip_display_settings": "Customize appearance, background, and theme.",
        "tooltip_history": "View and search past calculation results.",
        "tooltip_preprocess": "Configure image preprocessing for better OCR accuracy.",
        "tooltip_help": "Open the help documentation.",
        "tooltip_load_image": "Load an image file from disk.",
        "tooltip_paste": "Paste image from clipboard (Ctrl+V).",
        "tooltip_crop": "Crop the selected area for OCR processing.",
        "tooltip_auto_calculate": "Automatically calculate after loading/cropping image.",
        "tooltip_calculate": "Run score calculation with current values (F5).",
        "tooltip_set_equipped": "Save current values as the equipped echo for this character.",
        "tooltip_export_txt": "Export results to a text file (Ctrl+S).",
        "scoreboard": "Scoreboard",
        "tooltip_scoreboard": "Generate a scoreboard image.",
        "save_scoreboard": "Save Scoreboard",
        "tooltip_clear_all": "Clear all inputs and images (Ctrl+R).",
        "tooltip_clear_tab": "Clear only the current tab's content.",
        "tooltip_manual_mode": "Manually enter stats for calculation.",
        "tooltip_ocr_mode": "Automatically extract stats from images.",
        "tooltip_batch_mode": "Evaluate the entire 5-echo set.",
        "tooltip_single_mode": "Evaluate only the currently selected echo.",
        "apply_selection": "Apply Selection",
        "tooltip_apply_selection": "Applies the current drag-selected area to the main UI percentage sliders.",
    },
    "zh-CN": {
        "app_title": "鸣潮 音骸评分计算器",
        "char_setting_title": "角色设置",
        "char_name": "角色名称:",
        "char_name_en": "英文名:",
        "char_name_en_placeholder": "输入英文名称 (例如: Calcharo)",
        "cost_config": "Cost构成:",
        "echo_5_slot_config": "音骸5栏设置",
        "cost_echo": "Cost{} 音骸",
        "effective_substats_weights": "有效副属性与权重输入 (5栏)",
        "effective_substat_n": "有效副属性{}",
        "weight": "权重:",
        "save": "保存",
        "close": "关闭",
        "error": "错误",
        "enter_char_name": "请输入角色名称",
        "enter_char_name_en": "请输入英文名称",
        "base_stat_offsets": "基础属性/武器补正 (Character/Weapon Stat Offsets)",
        "scaling_stat_label": "参照属性:",
        "base_stat_label": "基础值 (角色+武器):",
        "ideal_stat_label": "理想值 (目标属性):",
        "crit_offset": "暴击补正:",
        "crit_offset_tooltip": "输入来自武器和基础属性的总暴击率。用于CV评分计算。",
        "echo_main_stat_unselected": "音骸{}主属性未选择",
        "save_complete": "保存完成",
        "save_msg": "{} 的设置已保存",
        "basic_settings": "基本设置",
        "character": "角色:",
        "input_mode": "输入:",
        "manual": "手动",
        "ocr": "OCR",
        "auto_main": "自动主属性",
        "auto_calculate": "自动计算",
        "calc_mode": "计算:",
        "methods_label": "评估方式:",
        "batch": "批量",
        "single_only": "单体",
        "calculate": "计算",
        "set_equipped": "设为当前装备",
        "vs_equipped": "与装备比较",
        "export_txt": "导出TXT",
        "clear_all": "全部清除",
        "clear_tab": "清除标签页",
        "char_setting": "角色设置",
        "help": "帮助",
        "ocr_image": "OCR图像",
        "load_image": "加载图像",
        "paste_clipboard": "从剪贴板粘贴 (Ctrl+V)",
        "perform_crop": "执行裁剪",
        "crop_mode": "裁剪模式:",
        "drag": "拖动",
        "percent": "%指定",
        "left_percent": "左%:",
        "top_percent": "上%:",
        "width_percent": "宽%:",
        "height_percent": "高%:",
        "no_image": "无图像",
        "calc_result": "计算结果",
        "log": "日志",
        "calculator": "计算",
        "settings": "设置",
        "general_settings": "常规设置",
        "calculation_settings": "计算设置",
        "ocr_settings": "OCR与裁剪",
        "actions": "操作",
        "main_stat": "主属性",
        "substats": "副属性",
        "ratio": "倍率: {}",
        "tab_clear_success": "标签页 '{}' 已清除",
        "export_success": "导出成功",
        "export_msg": "结果已导出为TXT文件。",
        "ocr_library_missing": "OCR模式需要以下库:\n{}\n\n退回到手动模式。",
        "ocr_auto_fill_fail_no_tab": "OCR自动输入失败: 未选择标签页",
        "ocr_auto_fill_fail_tab_not_found": "OCR自动输入失败: 未找到标签页'{}'",
        "ocr_auto_fill_success": "OCR自动输入: 副属性{} -> {} {}{}",
        "clipboard_no_image": "剪贴板中没有图像",
        "clipboard_error": "剪贴板读取错误: {}",
        "image_not_loaded": "图像未加载",
        "file_not_found": "未找到文件:\n{}",
        "image_select_cancelled": "图像选择已取消",
        "select_image_file": "选择图像文件",
        "image_files": "图像文件",
        "all_files": "所有文件",
        "pillow_required": "使用OCR模式需要Pillow。",
        "crop_cancel": "裁剪取消",
        "image_loaded": "图像已加载: {}",
        "ocr_success": "OCR成功 (字数: {})",
        "ocr_no_text": "OCR结果: 未检测到文本",
        "ocr_tesseract_not_found": "未找到Tesseract可执行文件 (设置: {})",
        "ocr_lang_data_error": "未找到OCR语言数据(chi_sim)。\n请安装Tesseract简体中文数据(chi_sim.traineddata)。\n详情: {}",
        "ocr_process_error": "OCR处理过程中发生错误:\n{}",
        "data_save_success": "数据保存成功",
        "data_load_success": "数据读取完成（已应用必要项）",
        "data_load_error": "读取失败: {}",
        "waiting_for_character": "请选择角色。选择后将执行计算。",
        "log_waiting_for_character": "由于未选择角色，计算已挂起。",
        "settings_loaded": "设置已加载",
        "language": "语言 (Language):",
        "restart_required": "需要重启",
        "restart_msg": "语言设置已更改。请重新启动应用程序以生效。",
        "language_changed_title": "语言更改",
        "language_changed_message": "语言设置已切换。",
        "score_calc_error": "评分计算错误: {}",
        "tab_not_selected": "未选择标签页",
        "tab_info_error": "标签页信息获取错误",
        "main_stat_missing": "{}: 主属性未输入",
        "individual_score_title": "【{}】个别评分计算 - {}\n",
        "echo_info": "【音骸信息】\n",
        "level": "等级: {}\n",
        "effective_substat_count": "有效副属性数: {}/5\n\n",
        "substat_header": "【副属性】\n",
        "none": "  （无）\n",
        "score_by_method": "【各方式评分】\n\n",
        "score_label": "   评分",
        "rating_label": "   评价",
        "desc_label": "   说明",
        "overall_eval": "【综合评估】\n",
        "estimated_total_stats": "【推定总属性】\n",
        "total_score": "综合评分",
        "overall_rating": "综合评价",
        "recommendation": "推荐度",
        "batch_score_title": "【{}】音骸套装综合评估\n",
        "calculated_count": "已计算音骸数: {}/{}\n",
        "avg_scores_title": "【{}个音骸的平均评分】",
        "average": "平均",
        "total_sum": "评分总计",
        "total_average": "综合平均",
        "echo_n_header": "\n【音骸 {}】{}\n",
        "set_total_score": "【套装总评分】\n",
        "set_avg_score": "【套装平均评分】\n",
        "final_evaluation": "【最终评估】\n",
        "achievement_rate_label": "完美达成率",
        "achievement_rate_desc": "以理想的5种副属性均为最大值为100%计算的达成度",
        "sss_desc": "SSS级 - 完美的音骸套装！理论上限级性能",
        "ss_desc": "SS级 - 非常优秀的套装。接近完成",
        "s_desc": "S级 - 优秀的套装。实战性能足够",
        "a_desc": "A级 - 良好的套装。使用没有问题",
        "b_desc": "B级 - 及格。有提升空间",
        "c_desc": "C级 - 需要改进。建议继续刷取",
        "normalized_score_desc": "将各副属性按最大值归一化并加权",
        "ratio_score_desc": "考虑副属性分配比率和伤害提升",
        "roll_quality_desc": "各副属性的Roll强度的个别评估",
        "effective_stat_desc": "为有效副属性数量提供加成",
        "normalized_score_label": "归一化评分方式 (GameWith式)",
        "ratio_score_label": "比例重视方式 (Keisan式)",
        "roll_quality_label": "Roll品质方式",
        "effective_stat_label": "有效属性数量方式",
        "cost_label": "Cost: {}",
        "score_point": "{:.2f}分",
        "score_per_item": "{:.2f}分/个",
        "score_point_count": "{:.2f}分 [{}个]",
        "total_score_label": "综合评分",
        "total_label": "综合",
        "normalized_label": "归一化",
        "ratio_label": "比例",
        "roll_label": "Roll",
        "effective_label": "有效副属",
        "effective_count_label": "有效数",
        "recommend_label": "推荐",
        "warning": "警告",
        "no_data": "无可计算的音骸数据",
        "individual_eval_done": "个别详细评估完成: {} - 综合{:.2f}分",
        "batch_eval_done": "批量评估完成: 已计算 {} 个音骸",
        "calc_error": "计算错误:\n{}",
        "batch_calc_error": "批量评估错误: {}",
        "batch_error_msg": "批量计算过程中发生错误:\n{}",
        "image_load_error": "图像加载失败:\n{}",
        "image_load_error_log": "图像加载错误: {}",
        "pytesseract_not_installed": "未安装pytesseract，无法执行OCR",
        "tesseract_found_path": "已在PATH中发现Tesseract: {}",
        "tesseract_not_found_sys": "未找到Tesseract。请设置路径或在系统中安装。",
        "ocr_error_title": "OCR错误",
        "ocr_lang_data_error_log": "OCR语言数据错误: {}",
        "tesseract_exec_not_found": "未找到Tesseract可执行文件:\n{}",
        "tesseract_exec_error_log": "Tesseract执行文件错误: {}",
        "ocr_process_error_log": "OCR处理错误: {}",
        "ocr_behavior": "OCR行为设置",
        "skip_duplicate_ocr": "忽略重复数据（跳过输入）",
        "tooltip_skip_duplicate_ocr": "启用后，将忽略与当前界面数据完全一致的OCR结果。\n防止意外再次OCR同一图像时导致的手动修改被重置。\n（独立于历史记录保存设置）",
        "crop_title": "图像裁剪",
        "crop_instruction": "请通过鼠标拖拽指定裁剪范围。",
        "crop_sync_notice": "※此处保存的位置(L,T)和大小(W,H)将与主界面的滑块(%指定)同步，并用于自动计算。",
        "echo_build_title": "音骸Build",
        "average_score_label": "平均评分",
        "cost_label_short": "Cost",
        "crop_confirm_apply": "确认应用",
        "crop_apply_percent": "应用为百分比区域",
        "crop_apply_percent_tooltip": "将所选区域的宽/高作为百分比，相对于原图进行比例裁剪。例如: 50% x 50%",
        "crop_save_as_default": "设置并与主界面滑块同步保存",
        "crop_save_as_default_tooltip": "立即将此范围(L,T,W,H)反映到主界面的滑块，并作为下次的默认值保存。",
        "crop_confirm_needed": "请勾选复选框以应用",
        "preset_name_placeholder": "名称",
        "preset_placeholder_format": "L,T,W,H (%)",
        "preset_name_required": "请输入预设名称",
        "preset_format": "预设格式不正确 (例如: 50x50)",
        "ok": "确定",
        "cancel": "取消",
        "reset": "重置",
        "load": "读取",
        "delete": "删除",
        "info": "信息",
        "crop_too_small": "选择范围太小",
        "text_color": "文本颜色:",
        "select_color": "选择颜色",
        "apply": "应用",
        "background_image": "背景图像:",
        "select_image": "选择图像",
        "clear_image": "清除",
        "bg_opacity": "背景不透明度:",
        "text_shadow": "启用文本阴影",
        "shadow_color": "阴影颜色:",
        "help_customization": "外观自定义 帮助",
        "font_settings": "字体设置",
        "font_family": "字体:",
        "default_font": "系统默认",
        "weight_template": "权重模板:",
        "custom": "自定义",
        "title_warning": "警告",
        "warn_legacy_bg_not_found": "在以下路径未找到之前设置的背景图像:\n\n{0}\n\n设置已清除。",
        # Stats
        "HP": "生命值",
        "HP%": "生命值%",
        "攻撃力": "攻击力",
        "攻撃力%": "攻击力%",
        "防御力": "防御力",
        "防御力%": "防御力%",
        "クリティカル率": "暴击率",
        "クリティカルダメージ": "暴击伤害",
        "共鳴効率": "共鸣效率",
        "通常攻撃ダメージアップ": "普攻伤害加成",
        "重撃ダメージアップ": "重击伤害加成",
        "共鳴スキルダメージアップ": "共鸣技能伤害加成",
        "共鳴解放ダメージアップ": "共鸣解放伤害加成",
        "焦熱ダメージアップ": "焦热伤害加成",
        "凝縮ダメージアップ": "凝缩伤害加成",
        "電導ダメージアップ": "电导伤害加成",
        "気動ダメージアップ": "气动伤害加成",
        "回折ダメージアップ": "回折伤害加成",
        "消滅ダメージアップ": "消灭伤害加成",
        "HP回復効果アップ": "治疗效果加成",
        # Ratings
        "rating_sss_norm": "SS级 - 最高品质",
        "rating_ss_norm": "S级 - 优秀",
        "rating_s_norm": "A级 - 实用",
        "rating_b_norm": "B级 - 需改进",
        "rating_perf_ratio": "完美 - 接近理论上限",
        "rating_exc_ratio": "优秀 - 已经很强",
        "rating_good_ratio": "良好 - 可用",
        "rating_avg_ratio": "普通 - 建议提升",
        "rating_weak_ratio": "较弱 - 需刷取",
        "rating_god_roll": "神抽 - 连续最高Roll",
        "rating_win_roll": "大胜 - 多数高品质Roll",
        "rating_avg_roll": "平均 - 标准Roll",
        "rating_bad_roll": "遗憾 - 低品质Roll",
        "rating_perf_eff": "完美 - 5有效属性 ({:.1f}分)",
        "rating_exc_eff": "优秀 - 4有效属性 ({:.1f}分)",
        "rating_good_eff": "良好 - 3有效属性 ({:.1f}分)",
        "rating_bad_eff": "需改进 - {}有效属性 ({:.1f}分)",
        "rating_sss_global": "SSS - 完美的音骸套装!",
        "rating_ss_global": "SS - 非常优秀",
        "rating_s_global": "S - 优秀",
        "rating_a_global": "A - 良好",
        "rating_b_global": "B - 及格",
        "rating_c_global": "C - 需改进",
        "rec_continue": "继续刷取",
        "rec_use": "推荐使用",
        "theme": "浅色/深色",
        "dark_theme": "深色",
        "light_theme": "浅色",
        "clear_theme": "清除",
        "custom_theme": "自定义",
        "display_settings": "显示设置",
        # Character Names
        "CarlottaNew": "卡洛塔New",
        "Cantarella": "坎塔雷拉",
        "Tsubaki": "椿",
        "Changli": "长离",
        "General": "通用",
        "rating_sss_single": "SSS - 完美的音骸! 理想的性能",
        "rating_ss_single": "SS - 非常优秀的音骸",
        "rating_s_single": "S - 优秀的音骸",
        "rating_a_single": "A - 良好的音骸",
        "rating_b_single": "B - 可用",
        "rating_c_single": "C - 建议继续刷取",
        # CV Method Ratings
        "rating_outstanding_cv": "最高级 - 45分以上 (SSS级)",
        "rating_excellent_cv": "非常优秀 - 38~45分 (S级)",
        "rating_good_cv": "优秀 - 30~38分 (目标达成)",
        "rating_acceptable_cv": "及格 - 25~30分 (最低限度)",
        "rating_weak_cv": "需努力 - 25分以下",
        # Method Labels
        "cv_score_label": "CV换算方式 (社区标准)",
        "cv_score_desc": "以双暴值为基准的评估 (30分及格/38分目标)",
        # Method Selection
        "calc_methods": "计算方式:",
        "method_normalized": "归一化",
        "method_ratio": "比例重视",
        "method_roll": "Roll品质",
        "method_effective": "有效属性数",
        "method_cv": "CV换算",
        "no_methods_selected": "请至少选择一种计算方式",
        "input_bg_color": "输入框背景颜色",
        "full_reset": "重置所有外观设置",
        "confirm_full_reset": "是否确定要重置所有外观设置？",
        "cleanup_title": "背景图像清理",
        "cleanup_button": "清理",
        "cleanup_no_folder": "未找到 images 文件夹。",
        "cleanup_no_unused": "没有未使用的背景图像。",
        "cleanup_confirm": "是否删除 {} 个未使用的图像？\n\n{}",
        "cleanup_error": "已删除 {} 个图像，但在删除以下文件时发生错误:\n\n{}",
        "cleanup_success": "已成功删除 {} 个未使用的图像。",
        "cleanup_unexpected_error": "清理过程中发生意外错误:\n{}",
        "new": "新建",
        "edit": "编辑",
        "char_setting_new": "角色设置(新建)",
        "char_setting_edit": "角色设置(编辑)",
        "history_title": "计算历史",
        "history": "历史",
        "preprocess_settings": "预处理设置",
        "history_search": "搜索:",
        "history_char": "角色:",
        "history_cost": "Cost:",
        "history_rating": "评价:",
        "history_from": "开始日期:",
        "history_to": "结束日期:",
        "history_filter_date": "按日期过滤",
        "history_reset": "重置",
        "history_clear": "清空历史",
        "history_stats": "计数: {} | 平均分: {:.2f} | 最高分: {:.2f}",
        "history_no_data": "当前条件下没有符合的记录。",
        "history_col_time": "时间",
        "history_col_char": "角色",
        "history_col_cost": "Cost",
        "history_col_action": "操作",
        "history_col_result": "结果",
        "history_duplicate_mode": "重复记录行为:",
        "history_dup_all": "全部保存 (允许重复)",
        "history_dup_latest": "保留最新 (删除旧记录)",
        "history_dup_oldest": "保留最久 (忽略新记录)",
        "history_duplicate_tooltip": "设置计算具有相同属性的音骸时的行为。\n・全部保存: 直接添加。\n・保留最新: 删除旧记录并以上次计算时间覆盖。\n・保留最久: 已有记录时不添加，维持最初计算的时间。",
        "select_character": "选择角色",
        "select_character_to_edit": "请选择要编辑的角色:",
        "no_characters_found": "未找到角色。",
        "tooltip_char_setting": "添加或编辑角色配置。",
        "tooltip_display_settings": "自定义背景、主题、文字颜色等外观。",
        "tooltip_history": "显示并搜索过去的计算结果记录。",
        "tooltip_preprocess": "进行旨在提高OCR精度的图像预处理设置。",
        "tooltip_help": "打开使用说明帮助文件。",
        "tooltip_load_image": "读取并显示图像文件。",
        "tooltip_paste": "读取剪贴板中的图像 (Ctrl+V)。",
        "tooltip_crop": "裁剪指定范围并用于OCR。",
        "tooltip_auto_calculate": "图像读取或OCR完成时自动执行计算。",
        "tooltip_calculate": "按当前输入值执行评分计算 (F5)。",
        "tooltip_set_equipped": "将当前输入内容保存为该角色的已装备音骸。",
        "tooltip_export_txt": "将计算结果输出到文本文件 (Ctrl+S)。",
        "scoreboard": "评分板",
        "tooltip_scoreboard": "生成评分板图像。",
        "save_scoreboard": "保存评分板",
        "tooltip_clear_all": "清除所有输入内容和图像 (Ctrl+R)。",
        "tooltip_clear_tab": "仅清除当前显示的标签页内容。",
        "tooltip_manual_mode": "手动输入数值进行计算的模式。",
        "tooltip_ocr_mode": "从图像自动识别数值进行计算的模式。",
        "tooltip_batch_mode": "评估整个5音骸组合。",
        "tooltip_single_mode": "仅评估当前选择的单个音骸。",
        "apply_selection": "应用选择范围",
        "tooltip_apply_selection": "将当前拖动选择的范围应用到主界面的百分比滑块中。"
    }
}
